sudo: true
language: python
python:
  - "3.5"
cache: pip
services:
  - mysql
before_install:
  - sudo apt-get update
  - sudo apt-get install python-html5lib
  - sudo apt-get install libmysqlclient-dev -y
install:
  - pip install -r requirements.txt
script:
  - export PYTHONPATH="$PYTHONPATH:$HOME/.python"
  - py.test
