# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='total_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
