# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170201_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
