# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='screen_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
